import { createHash } from "node:crypto"
import path from "node:path"
import { fileURLToPath } from "node:url"

const directory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const snapshotPrefix = "// Auto-generated by sync-models-catalog.ts - do not edit\nexport const snapshot = "

export const modelsCatalogPaths = {
  snapshot: path.join(directory, "src/provider/models-snapshot.js"),
  declaration: path.join(directory, "src/provider/models-snapshot.d.ts"),
  metadata: path.join(directory, "src/provider/models-snapshot.meta.json"),
}

export const modelsCatalogSchemaVersion = 1

export type ModelsCatalogMetadata = {
  schemaVersion: number
  source: string
  fetchedAt: string
  sha256: string
  providers: number
  models: number
}

export function validateModelsCatalog(value: unknown) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("models catalog must be an object keyed by provider ID")
  }

  const providers = Object.entries(value as Record<string, unknown>).filter(([, provider]) => {
    if (!provider || typeof provider !== "object" || Array.isArray(provider)) return false
    const models = (provider as { models?: unknown }).models
    return !!models && typeof models === "object" && !Array.isArray(models)
  })
  if (providers.length === 0) throw new Error("models catalog does not contain any provider models")

  for (const providerID of ["openai", "anthropic", "google"]) {
    const provider = (value as Record<string, { models?: Record<string, unknown> }>)[providerID]
    if (!provider || !provider.models || Object.keys(provider.models).length === 0) {
      throw new Error(`models catalog is missing required provider ${providerID}`)
    }
  }

  return {
    providers: providers.length,
    models: providers.reduce((total, [, provider]) => total + Object.keys((provider as { models: object }).models).length, 0),
  }
}

export async function readBundledModelsCatalog() {
  const source = await Bun.file(modelsCatalogPaths.snapshot).text()
  if (!source.startsWith(snapshotPrefix)) throw new Error("models catalog snapshot has an unexpected format")
  const catalog = JSON.parse(source.slice(snapshotPrefix.length)) as Record<string, unknown>
  const summary = validateModelsCatalog(catalog)
  return { catalog, source: JSON.stringify(catalog), ...summary }
}

export async function readBundledModelsCatalogMetadata() {
  const metadata = (await Bun.file(modelsCatalogPaths.metadata).json()) as ModelsCatalogMetadata
  if (metadata.schemaVersion !== modelsCatalogSchemaVersion) {
    throw new Error(`unsupported models catalog schema version ${metadata.schemaVersion}`)
  }
  return metadata
}

export async function ensureBundledModelsCatalog() {
  const snapshot = await readBundledModelsCatalog()
  const metadata = await readBundledModelsCatalogMetadata()
  const sha256 = createHash("sha256").update(snapshot.source).digest("hex")
  if (metadata.sha256 !== sha256) throw new Error("models catalog snapshot hash does not match its metadata")
  if (metadata.providers !== snapshot.providers || metadata.models !== snapshot.models) {
    throw new Error("models catalog metadata counts do not match its snapshot")
  }
  return { ...snapshot, metadata }
}

export async function writeBundledModelsCatalog(input: { catalog: unknown; source: string; fetchedAt?: string }) {
  const summary = validateModelsCatalog(input.catalog)
  const source = JSON.stringify(input.catalog)
  const metadata: ModelsCatalogMetadata = {
    schemaVersion: modelsCatalogSchemaVersion,
    source: input.source,
    fetchedAt: input.fetchedAt ?? new Date().toISOString(),
    sha256: createHash("sha256").update(source).digest("hex"),
    providers: summary.providers,
    models: summary.models,
  }
  await Bun.write(modelsCatalogPaths.snapshot, snapshotPrefix + source + "\n")
  await Bun.write(
    modelsCatalogPaths.declaration,
    "// Auto-generated by sync-models-catalog.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n",
  )
  await Bun.write(modelsCatalogPaths.metadata, JSON.stringify(metadata, null, 2) + "\n")
  return metadata
}
