const LANGUAGE_BY_EXTENSION = new Map([
  [".d.ts", "typescript"],
  [".ts", "typescript"],
  [".tsx", "typescript"],
  [".js", "javascript"],
  [".jsx", "javascript"],
  [".mjs", "javascript"],
  [".cjs", "javascript"],
  [".json", "json"],
  [".jsonc", "json"],
  [".json5", "json"],
  [".yaml", "yaml"],
  [".yml", "yaml"],
  [".toml", "ini"],
  [".ini", "ini"],
  [".cfg", "ini"],
  [".conf", "ini"],
  [".properties", "ini"],
  [".xml", "xml"],
  [".svg", "xml"],
  [".sql", "sql"],
  [".txt", "plaintext"],
  [".log", "plaintext"],
  [".env", "plaintext"],
  [".cpp", "cpp"],
  [".cc", "cpp"],
  [".cxx", "cpp"],
  [".c++", "cpp"],
  [".c", "c"],
  [".hpp", "cpp"],
  [".hh", "cpp"],
  [".hxx", "cpp"],
  [".h", "cpp"],
  [".py", "python"],
  [".pyi", "python"],
  [".ps1", "powershell"],
  [".psm1", "powershell"],
  [".psd1", "powershell"],
  [".bat", "bat"],
  [".cmd", "bat"],
  [".md", "markdown"],
  [".markdown", "markdown"],
  [".html", "html"],
  [".htm", "html"],
  [".css", "css"],
  [".scss", "scss"],
  [".less", "less"],
  [".sh", "shell"],
  [".bash", "shell"],
  [".zsh", "shell"],
  [".cs", "csharp"],
  [".java", "java"],
  [".go", "go"],
  [".rs", "rust"],
  [".php", "php"],
  [".rb", "ruby"],
  [".kt", "kotlin"],
  [".kts", "kotlin"],
  [".swift", "swift"],
  [".scala", "scala"],
  [".lua", "lua"],
  [".r", "r"],
  [".graphql", "graphql"],
  [".gql", "graphql"],
  [".proto", "protobuf"],
  [".vue", "html"],
  [".svelte", "html"],
  [".mdx", "markdown"],
]) as Map<string, string>

const LANGUAGE_BY_FILENAME = new Map([
  ["dockerfile", "dockerfile"],
  ["makefile", "shell"],
  [".gitignore", "ini"],
  [".editorconfig", "ini"],
]) as Map<string, string>

const EXTENSION_BY_FENCE_LANGUAGE = new Map([
  ["typescript", ".ts"],
  ["ts", ".ts"],
  ["tsx", ".tsx"],
  ["javascript", ".js"],
  ["js", ".js"],
  ["jsx", ".jsx"],
  ["json", ".json"],
  ["yaml", ".yaml"],
  ["yml", ".yml"],
  ["toml", ".toml"],
  ["ini", ".ini"],
  ["xml", ".xml"],
  ["svg", ".svg"],
  ["sql", ".sql"],
  ["text", ".txt"],
  ["plaintext", ".txt"],
  ["cpp", ".cpp"],
  ["c++", ".cpp"],
  ["cc", ".cpp"],
  ["cxx", ".cpp"],
  ["c", ".c"],
  ["python", ".py"],
  ["py", ".py"],
  ["powershell", ".ps1"],
  ["pwsh", ".ps1"],
  ["ps1", ".ps1"],
  ["bat", ".bat"],
  ["markdown", ".md"],
  ["md", ".md"],
  ["html", ".html"],
  ["css", ".css"],
  ["scss", ".scss"],
  ["less", ".less"],
  ["shell", ".sh"],
  ["shellscript", ".sh"],
  ["bash", ".sh"],
  ["sh", ".sh"],
  ["zsh", ".zsh"],
  ["csharp", ".cs"],
  ["c#", ".cs"],
  ["java", ".java"],
  ["go", ".go"],
  ["rust", ".rs"],
  ["rs", ".rs"],
  ["php", ".php"],
  ["ruby", ".rb"],
  ["rb", ".rb"],
  ["kotlin", ".kt"],
  ["kt", ".kt"],
  ["swift", ".swift"],
  ["scala", ".scala"],
  ["lua", ".lua"],
  ["r", ".r"],
  ["graphql", ".graphql"],
  ["proto", ".proto"],
  ["dockerfile", ".dockerfile"],
]) as Map<string, string>

const LANGUAGE_BY_HINT = new Map([
  ["typescript", "typescript"],
  ["ts", "typescript"],
  ["tsx", "typescript"],
  ["javascript", "javascript"],
  ["js", "javascript"],
  ["jsx", "javascript"],
  ["json", "json"],
  ["jsonc", "json"],
  ["yaml", "yaml"],
  ["yml", "yaml"],
  ["toml", "ini"],
  ["ini", "ini"],
  ["xml", "xml"],
  ["svg", "xml"],
  ["sql", "sql"],
  ["text", "plaintext"],
  ["plaintext", "plaintext"],
  ["cpp", "cpp"],
  ["c++", "cpp"],
  ["cc", "cpp"],
  ["cxx", "cpp"],
  ["hpp", "cpp"],
  ["h", "cpp"],
  ["c", "c"],
  ["python", "python"],
  ["py", "python"],
  ["powershell", "powershell"],
  ["pwsh", "powershell"],
  ["ps1", "powershell"],
  ["bat", "bat"],
  ["cmd", "bat"],
  ["markdown", "markdown"],
  ["md", "markdown"],
  ["html", "html"],
  ["htm", "html"],
  ["css", "css"],
  ["scss", "scss"],
  ["less", "less"],
  ["shell", "shell"],
  ["shellscript", "shell"],
  ["bash", "shell"],
  ["sh", "shell"],
  ["zsh", "shell"],
  ["csharp", "csharp"],
  ["c#", "csharp"],
  ["cs", "csharp"],
  ["java", "java"],
  ["go", "go"],
  ["rust", "rust"],
  ["rs", "rust"],
  ["php", "php"],
  ["ruby", "ruby"],
  ["rb", "ruby"],
  ["kotlin", "kotlin"],
  ["kt", "kotlin"],
  ["swift", "swift"],
  ["scala", "scala"],
  ["lua", "lua"],
  ["r", "r"],
  ["graphql", "graphql"],
  ["gql", "graphql"],
  ["protobuf", "protobuf"],
  ["proto", "protobuf"],
  ["dockerfile", "dockerfile"],
  ["vue", "html"],
  ["svelte", "html"],
  ["mdx", "markdown"],
]) as Map<string, string>

export function getCodeEditorLanguage(path?: string) {
  if (!path) return
  const normalized = path.toLowerCase()
  const filename = normalized.split(/[\\/]/).at(-1)
  if (filename) {
    const named = LANGUAGE_BY_FILENAME.get(filename)
    if (named) return named
  }
  const match = Array.from(LANGUAGE_BY_EXTENSION.keys()).find((ext) => normalized.endsWith(ext))
  if (!match) return
  return LANGUAGE_BY_EXTENSION.get(match)
}

export function isCodeEditorLanguageSupported(path?: string) {
  return Boolean(getCodeEditorLanguage(path))
}

export function getCodeEditorLanguageFromHint(language?: string) {
  if (!language) return
  return LANGUAGE_BY_HINT.get(language.toLowerCase())
}

export function getCodeEditorFenceExtension(language?: string) {
  if (!language) return
  return EXTENSION_BY_FENCE_LANGUAGE.get(language.toLowerCase())
}

export function isCodeEditorFenceLanguageSupported(language?: string) {
  return Boolean(getCodeEditorFenceExtension(language))
}
